In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('kc_house_data_train.csv')

In [3]:
df.head()

Unnamed: 0          id             date      price  bedrooms  bathrooms  \
0           0  2591820310  20141006T000000   365000.0         4       2.25   
1           1  7974200820  20140821T000000   865000.0         5       3.00   
2           2  7701450110  20140815T000000  1038000.0         4       2.50   
3           3  9522300010  20150331T000000  1490000.0         3       3.50   
4           4  9510861140  20140714T000000   711000.0         3       2.50   

   sqft_living  sqft_lot  floors  waterfront  ...  grade  sqft_above  \
0         2070      8893     2.0           0  ...      8        2070   
1         2900      6730     1.0           0  ...      8        1830   
2         3770     10893     2.0           0  ...     11        3770   
3         4560     14608     2.0           0  ...     12        4560   
4         2550      5376     2.0           0  ...      9        2550   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1986             0    98058  47.4388 -122.162   
1           1070      1977             0    98115  47.6784 -122.285   
2              0      1997             0    98006  47.5646 -122.129   
3              0      1990             0    98034  47.6995 -122.228   
4              0      2004             0    98052  47.6647 -122.083   

   sqft_living15  sqft_lot15  
0           2390        7700  
1           2370        6283  
2           3710        9685  
3           4050       14226  
4           2250        4050  

[5 rows x 22 columns]

In [4]:
df.columns

Index(['Unnamed: 0', 'id', 'date', 'price', 'bedrooms', 'bathrooms',
       'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition',
       'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated',
       'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [5]:
df.drop(['Unnamed: 0', 'id', 'lat','long'], axis =1, inplace = True)

In [6]:
df['date'] = df.date.astype(str)

Just getting the month from date

In [7]:
df['date'] = [x[4:6] for x in df['date']]

In [8]:
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0   10   365000.0         4       2.25         2070      8893     2.0   
1   08   865000.0         5       3.00         2900      6730     1.0   
2   08  1038000.0         4       2.50         3770     10893     2.0   
3   03  1490000.0         3       3.50         4560     14608     2.0   
4   07   711000.0         3       2.50         2550      5376     2.0   

   waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  \
0           0     0          4      8        2070              0      1986   
1           0     0          5      8        1830           1070      1977   
2           0     2          3     11        3770              0      1997   
3           0     2          3     12        4560              0      1990   
4           0     0          3      9        2550              0      2004   

   yr_renovated  zipcode  sqft_living15  sqft_lot15  
0             0    98058           2390        7700  
1             0    98115           2370        6283  
2             0    98006           3710        9685  
3             0    98034           4050       14226  
4             0    98052           2250        4050

Ranking the grade 1-5 (1 being the best)

In [9]:
df['grade'].unique()

array([ 8, 11, 12,  9,  7,  6, 10,  5, 13,  4,  3,  1])

In [10]:
df['bedrooms'].unique()

array([ 4,  5,  3,  2,  6,  1,  7,  0,  8, 11,  9, 10, 33])

In [11]:
df[df.bedrooms == 33]

date     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
8597   06  640000.0        33       1.75         1620      6000     1.0   

      waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  \
8597           0     0          5      7        1040            580      1947   

      yr_renovated  zipcode  sqft_living15  sqft_lot15  
8597             0    98103           1330        4700

In [12]:
df['date'][8597]

'06'

In [13]:
df.drop([8597], axis = 0, inplace = True)

In [14]:
df['home_age'] = [2015 - x for x in df['yr_built']]

In [15]:
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0   10   365000.0         4       2.25         2070      8893     2.0   
1   08   865000.0         5       3.00         2900      6730     1.0   
2   08  1038000.0         4       2.50         3770     10893     2.0   
3   03  1490000.0         3       3.50         4560     14608     2.0   
4   07   711000.0         3       2.50         2550      5376     2.0   

   waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  \
0           0     0          4      8        2070              0      1986   
1           0     0          5      8        1830           1070      1977   
2           0     2          3     11        3770              0      1997   
3           0     2          3     12        4560              0      1990   
4           0     0          3      9        2550              0      2004   

   yr_renovated  zipcode  sqft_living15  sqft_lot15  home_age  
0             0    98058           2390        7700        29  
1             0    98115           2370        6283        38  
2             0    98006           3710        9685        18  
3             0    98034           4050       14226        25  
4             0    98052           2250        4050        11

In [16]:
df.drop('yr_built', axis =1, inplace =True)

In [17]:
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0   10   365000.0         4       2.25         2070      8893     2.0   
1   08   865000.0         5       3.00         2900      6730     1.0   
2   08  1038000.0         4       2.50         3770     10893     2.0   
3   03  1490000.0         3       3.50         4560     14608     2.0   
4   07   711000.0         3       2.50         2550      5376     2.0   

   waterfront  view  condition  grade  sqft_above  sqft_basement  \
0           0     0          4      8        2070              0   
1           0     0          5      8        1830           1070   
2           0     2          3     11        3770              0   
3           0     2          3     12        4560              0   
4           0     0          3      9        2550              0   

   yr_renovated  zipcode  sqft_living15  sqft_lot15  home_age  
0             0    98058           2390        7700        29  
1             0    98115           2370        6283        38  
2             0    98006           3710        9685        18  
3             0    98034           4050       14226        25  
4             0    98052           2250        4050        11

In [20]:
import statsmodels.api as m
from statsmodels.formula.api import ols
import matplotlib.pyplot as plt
plt.style.use('seaborn')

In [21]:
model = ols(formula = 'price~date+bedrooms+bathrooms+sqft_living+sqft_lot+floors+waterfront+view+condition+grade+sqft_above+sqft_basement+yr_renovated+zipcode+sqft_living15+sqft_lot15+home_age', data=df).fit()

In [22]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.656
Model:                            OLS   Adj. R-squared:                  0.655
Method:                 Least Squares   F-statistic:                     1265.
Date:                Thu, 20 Feb 2020   Prob (F-statistic):               0.00
Time:                        13:25:20   Log-Likelihood:            -2.3713e+05
No. Observations:               17289   AIC:                         4.743e+05
Df Residuals:                   17262   BIC:                         4.745e+05
Df Model:                          26                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept     -2.273e+06   3.48e+06     -0.653      0.514    -9.1e+06    4.55e+06
date[T.02]     4284.1870   1.05e+04      0.410      0.682   -1.62e+04    2.48e+04
date[T.03]     3.432e+04   9636.568      3.561      0.000    1.54e+04    5.32e+04
date[T.04]     3.957e+04   9348.589      4.233      0.000    2.12e+04    5.79e+04
date[T.05]     1.269e+04   9262.615      1.370      0.171   -5464.468    3.08e+04
date[T.06]     8104.4394   9401.501      0.862      0.389   -1.03e+04    2.65e+04
date[T.07]    -1716.4307   9391.046     -0.183      0.855   -2.01e+04    1.67e+04
date[T.08]     9018.3125   9572.892      0.942      0.346   -9745.526    2.78e+04
date[T.09]    -7083.7870   9767.078     -0.725      0.468   -2.62e+04    1.21e+04
date[T.10]     4370.2844   9642.373      0.453      0.650   -1.45e+04    2.33e+04
date[T.11]     2287.0717   1.01e+04      0.226      0.821   -1.76e+04    2.21e+04
date[T.12]    -2561.0745   1.01e+04     -0.254      0.800   -2.23e+04    1.72e+04
bedrooms      -4.369e+04   2374.720    -18.398      0.000   -4.83e+04    -3.9e+04
bathrooms      4.697e+04   3960.318     11.860      0.000    3.92e+04    5.47e+04
sqft_living     114.1683      2.765     41.293      0.000     108.749     119.588
sqft_lot         -0.0131      0.056     -0.236      0.813      -0.122       0.096
floors          2.51e+04   4350.409      5.770      0.000    1.66e+04    3.36e+04
waterfront     5.887e+05   2.06e+04     28.537      0.000    5.48e+05    6.29e+05
view           4.233e+04   2568.128     16.483      0.000    3.73e+04    4.74e+04
condition      2.086e+04   2854.783      7.308      0.000    1.53e+04    2.65e+04
grade          1.188e+05   2566.321     46.273      0.000    1.14e+05    1.24e+05
sqft_above       54.8823      2.705     20.290      0.000      49.581      60.184
sqft_basement    59.2860      3.179     18.649      0.000      53.055      65.517
yr_renovated      7.8071      4.455      1.752      0.080      -0.926      16.540
zipcode          12.8641     35.494      0.362      0.717     -56.707      82.436
sqft_living15    26.1586      4.143      6.313      0.000      18.037      34.280
sqft_lot15       -0.5141      0.087     -5.894      0.000      -0.685      -0.343
home_age       3600.9934     84.604     42.563      0.000    3435.161    3766.825
==============================================================================
Omnibus:                    13660.339   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1132614.105
Skew:                           3.214   Prob(JB):                         0.00
Kurtosis:                      42.127   Cond. No.                     1.01e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of

In [23]:
month_dummies = pd.get_dummies(df['date'], prefix= 'month', drop_first =True)

In [24]:
df = pd.concat([df, month_dummies], axis =1)

In [25]:
df.drop('date', axis = 1, inplace =True)

In [26]:
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   365000.0         4       2.25         2070      8893     2.0           0   
1   865000.0         5       3.00         2900      6730     1.0           0   
2  1038000.0         4       2.50         3770     10893     2.0           0   
3  1490000.0         3       3.50         4560     14608     2.0           0   
4   711000.0         3       2.50         2550      5376     2.0           0   

   view  condition  grade  ...  month_03  month_04  month_05  month_06  \
0     0          4      8  ...         0         0         0         0   
1     0          5      8  ...         0         0         0         0   
2     2          3     11  ...         0         0         0         0   
3     2          3     12  ...         1         0         0         0   
4     0          3      9  ...         0         0         0         0   

   month_07  month_08  month_09  month_10  month_11  month_12  
0         0         0         0         1         0         0  
1         0         1         0         0         0         0  
2         0         1         0         0         0         0  
3         0         0         0         0         0         0  
4         1         0         0         0         0         0  

[5 rows x 28 columns]

In [27]:
zipcode_dummies = pd.get_dummies(df['zipcode'], prefix ='zipc', drop_first =True)


In [28]:
df = pd.concat([df, zipcode_dummies], axis =1)

In [29]:
df.drop('zipcode', axis = 1, inplace =True)

#### OLS

In [32]:
outcome = 'price'
predictors = df.drop('price', axis = 1)
predictorsplus = '+'.join(predictors.columns)
formula = outcome + '~' + predictorsplus

In [33]:
model = ols(formula=formula, data = df).fit()

In [34]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.806
Model:                            OLS   Adj. R-squared:                  0.805
Method:                 Least Squares   F-statistic:                     761.1
Date:                Thu, 20 Feb 2020   Prob (F-statistic):               0.00
Time:                        14:15:47   Log-Likelihood:            -2.3217e+05
No. Observations:               17289   AIC:                         4.645e+05
Df Residuals:                   17194   BIC:                         4.653e+05
Df Model:                          94                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept     -5.471e+05   1.94e+04    -28.211      0.000   -5.85e+05   -5.09e+05
bedrooms      -3.075e+04   1813.539    -16.956      0.000   -3.43e+04   -2.72e+04
bathrooms      2.477e+04   3010.018      8.229      0.000    1.89e+04    3.07e+04
sqft_living     117.3472      2.102     55.827      0.000     113.227     121.467
sqft_lot          0.2151      0.042      5.102      0.000       0.132       0.298
floors        -4.591e+04   3612.959    -12.708      0.000    -5.3e+04   -3.88e+04
waterfront     6.675e+05   1.58e+04     42.308      0.000    6.37e+05    6.98e+05
view           5.451e+04   1992.380     27.358      0.000    5.06e+04    5.84e+04
condition      2.648e+04   2204.877     12.009      0.000    2.22e+04    3.08e+04
grade          5.614e+04   2083.350     26.945      0.000    5.21e+04    6.02e+04
sqft_above       99.0491      2.171     45.626      0.000      94.794     103.304
sqft_basement    18.2980      2.484      7.365      0.000      13.428      23.168
yr_renovated     17.2330      3.385      5.090      0.000      10.597      23.869
sqft_living15     9.7496      3.313      2.943      0.003       3.256      16.244
sqft_lot15       -0.0845      0.068     -1.242      0.214      -0.218       0.049
home_age        737.8503     74.475      9.907      0.000     591.871     883.829
month_02       2504.3163   7875.639      0.318      0.751   -1.29e+04    1.79e+04
month_03       2.312e+04   7256.781      3.185      0.001    8892.432    3.73e+04
month_04         3.2e+04   7041.855      4.545      0.000    1.82e+04    4.58e+04
month_05        587.9024   6979.331      0.084      0.933   -1.31e+04    1.43e+04
month_06        190.7093   7082.247      0.027      0.979   -1.37e+04    1.41e+04
month_07      -8791.8876   7077.152     -1.242      0.214   -2.27e+04    5080.052
month_08      -2354.5568   7213.502     -0.326      0.744   -1.65e+04    1.18e+04
month_09      -1.355e+04   7356.756     -1.842      0.065    -2.8e+04     867.208
month_10      -5437.5291   7262.465     -0.749      0.454   -1.97e+04    8797.643
month_11      -9557.1145   7623.980     -1.254      0.210   -2.45e+04    5386.665
month_12      -7802.7743   7601.692     -1.026      0.305   -2.27e+04    7097.317
zipc_98002     2.547e+04   1.64e+04      1.548      0.122   -6772.129    5.77e+04
zipc_98003    -1.724e+04   1.47e+04     -1.169      0.242   -4.61e+04    1.17e+04
zipc_98004     7.933e+05   1.47e+04     53.813      0.000    7.64e+05    8.22e+05
zipc_98005     2.904e+05   1.72e+04     16.874      0.000    2.57e+05    3.24e+05
zipc_98006     2.618e+05   1.32e+04     19.899      0.000    2.36e+05    2.88e+05
zipc_98007     2.461e+05   1.79e+04     13.739      0.000    2.11e+05    2.81e+05
zipc_98008     2.452e+05   1.48e+04     16.604      0.000    2.16e+05    2.74e+05
zipc_98010     6.301e+04   2.16e+04      2.916   

#### Linear Regression

In [36]:
from sklearn.linear_model import LinearRegression
y = df['price']
linreg = LinearRegression()
linreg.fit(predictors,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
linreg.coef_, linreg.intercept_

#### RFE

In [40]:
from sklearn.feature_selection import RFE
selector = RFE(linreg)
selector = selector.fit(predictors, df['price'])

In [41]:
selector.support_

array([False, False,  True, False, False,  True, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True, False,  True, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False,  True,  True, False,  True,  True, False, False,  True,
        True, False, False, False, False, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False, False,
        True, False, False, False,  True])

In [43]:
estimators = selector.estimator_

In [44]:
estimators.coef_

array([-5.71593963e+14,  8.88924453e+05,  5.71593963e+14,  5.71593963e+14,
        8.07073323e+05,  2.98694909e+05,  3.05104401e+05,  2.01866935e+05,
        2.40654253e+05,  8.42010547e+04,  1.50819710e+05,  1.71342497e+05,
        8.44540600e+04,  1.98220813e+05,  3.46055917e+05,  1.84237233e+05,
        1.36784475e+06,  5.56276057e+05,  2.07248443e+05,  1.65066241e+05,
        1.22331600e+05,  1.62546032e+05,  1.59512133e+05,  1.16603502e+05,
        5.13625950e+05,  3.40944505e+05,  4.91807653e+05,  1.06470361e+05,
        3.56375309e+05,  1.02466833e+05,  5.46692759e+05,  6.46429130e+05,
        3.30139382e+05,  3.18577387e+05,  3.31191458e+05,  1.72789494e+05,
        5.34575658e+05,  3.29936089e+05,  1.99693363e+05,  2.01616073e+05,
        1.47158844e+05,  2.77420872e+05,  2.91959927e+05,  9.88764939e+04,
        1.38485764e+05,  2.63206209e+05,  4.20295994e+05])

#### Cross Validation 

In [46]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score

In [47]:
cv_10 = np.mean(cross_val_score(linreg, predictors, df['price'], cv=10, scoring ='neg_mean_squared_error'))

#### Split and Train the data

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(predictors, df['price'], test_size = 0.2, random_state = 42)

In [65]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()


In [66]:
linreg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [67]:
y_hat_train = linreg.predict(X_train)
y_hat_test = linreg.predict(X_test)

In [68]:
from sklearn.metrics import mean_squared_error
train_mse = mean_squared_error(y_train, y_hat_train)
test_mse = mean_squared_error(y_test, y_hat_test)

In [70]:
train_mse, test_mse

(27256272766.89356, 26197356578.014507)

#### Testing Data

In [71]:
testdf = pd.read_csv('kc_house_data_test_features.csv')

In [74]:
testdf.drop(['Unnamed: 0', 'id', 'lat','long'], axis =1, inplace =True)

In [79]:
testdf['date'] = [x[4:6] for x in testdf['date']]

In [80]:
testdf['home_age'] = [2015 - x for x in testdf['yr_built']]

In [81]:
testdf.drop('yr_built', axis =1, inplace =True)

In [85]:
month_dummies = pd.get_dummies(testdf['date'], prefix= 'month', drop_first =True)
testdf = pd.concat([testdf, month_dummies], axis =1)
testdf.drop('date', axis = 1, inplace =True)

In [86]:
zipcode_dummies = pd.get_dummies(testdf['zipcode'], prefix ='zipc', drop_first =True)
testdf = pd.concat([testdf, zipcode_dummies], axis =1)
testdf.drop('zipcode', axis = 1, inplace =True)

In [88]:
final_preds = linreg.predict(testdf)

In [91]:
final_preds

array([560953.07291191, 564725.12694301, 366154.24274933, ...,
       317494.08437773, 392089.93218911, 312970.33359738])

In [93]:
final_preds = pd.Series(final_preds)

In [94]:
final_preds.to_csv('housing_preds_RL.csv', index = False)

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.


In [95]:
pd.read_csv('housing_preds_RL.csv')

560953.072911914
0        564725.126943
1        366154.242749
2        282135.320809
3        565389.447395
4        591356.511324
...                ...
4317     506121.795748
4318     455456.335284
4319     317494.084378
4320     392089.932189
4321     312970.333597

[4322 rows x 1 columns]